# Generated by Django 4.2.8 on 2023-12-11 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('first_leader', models.CharField(max_length=100)),
                ('board_of_directors', models.CharField(max_length=100)),
                ('chairman', models.CharField(max_length=100)),
                ('board_members', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=100)),
                ('chief_accountant', models.CharField(max_length=100)),
                ('BIN', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('license', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOrganizationNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_published', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_organization.financialorganization')),
            ],
        ),
    ]
